name: CI Tests and Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test on Node.js ${{ matrix.node_version }} and platform ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14.x, 16.x, 17.x]
        platform: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          args: install:ci

      - name: Install dependencies
        run: yarn install:ci

  build:
    name: Build on Node.js ${{ matrix.node_version }} and platform ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14.x, 16.x, 17.x]
        platform: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn install:ci

      - name: Build
        run: yarn build

